version = 0.1

[default.deploy.parameters]
stack_name = "verify-and-extract-player-data-v2"
resolve_s3 = true
s3_prefix = "verify-and-extract-player-data-v2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
