version = 0.1

[default.deploy.parameters]
stack_name = "create-schedules"
resolve_s3 = true
s3_prefix = "create-schedules"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
